### PR TITLE
feat: move ad creation inline to ad set

### PR DESCRIPTION
**Pull request by IanKrieger**
Moves ad creation inline to ad sets

---

https://github.com/brave/ads-ui/assets/48930920/47ff79ea-47fd-4d75-8c99-48a336a9096a

### CODE REVIEW

**Review by tackley — APPROVED** [review]
I'm not 100% sure I'm a fan of making another container appear inline when you click to add a new ad - it feels like me like a modal would work better in this case - but this is a step forward from where we are today.

**Review by lukaslevert — APPROVED** [review]
This is awesome! Think it's a great improvement. Nice @IanKrieger

**Comment by IanKrieger** [comment]
@lukaslevert + @tackley took your suggestion of the modal and ran with it anyway, please review updated demo at your earliest conveniences

**Review by lukaslevert — APPROVED** [review]
This is great—

One suggestion, can we keep the width of the news card static when adding text? I noticed it was moving around as your copy got longer, before it reached some max width and then stopped.

**Pull request merged**
